### ISSUE TITLE
Error: Minified React error #130 after deploy

### ISSUE THREAD

**Issue by selcukguler0** [erdigokce/turkey-map-react#10]
Everything working fine at local. After deploy getting this error. 
https://weather.selcukguler.com/
https://github.com/selcukguler0/weather_app

```
index.99339086.js:32 Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Tn (index.99339086.js:32:49682)
    at y (index.99339086.js:30:17372)
    at We (index.99339086.js:32:1494)
    at to (index.99339086.js:32:44706)
    at Z0 (index.99339086.js:32:40003)
    at Ou (index.99339086.js:32:39931)
    at rr (index.99339086.js:32:39785)
    at _5 (index.99339086.js:32:36120)
    at E9 (index.99339086.js:32:36932)
    at w2 (index.99339086.js:30:3274)
Tn @ index.99339086.js:32
y @ index.99339086.js:30
We @ index.99339086.js:32
to @ index.99339086.js:32
Z0 @ index.99339086.js:32
Ou @ index.99339086.js:32
rr @ index.99339086.js:32
_5 @ index.99339086.js:32
E9 @ index.99339086.js:32
w2 @ index.99339086.js:30
(anonymous) @ index.99339086.js:32
```

**Comment by erdigokce** [comment]
Hi @selcukguler0 ,

Can you please provide more details like "relevant" code block, component props etc.?

The repo you shared is inaccessible. Also I have tried to run a production build of Next.js there was no error. Your detailed case would be great.

**Comment by utkucanakbay** [comment]
We are getting the same error in our project. Is the problem solved? If it is solved, can you share the solution?

**Comment by erdigokce** [comment]
Please upgrade to the latest version. Closed until reoccurs.
